export default {
  Common:{
    goBack:require('../img/icon_back_white.png'),
    arrowRight:require('../img/icon_arrow_right_white.png'),
    close:require('../img/icon_close_gray.png'),
    empty:require('../img/icon_empty.png'),
  },
  Main:{
    homeTabNormal:require('../img/icon_elm_gray.png'),
    homeTabClick:require('../img/icon_elm_blue.png'),
    findTabNormal:require('../img/icon_find_gray.png'),
    findTabClick:require('../img/icon_find_blue.png'),
    orderTabNormal:require('../img/icon_order_gray.png'),
    orderTabClick:require('../img/icon_order_blue.png'),
    myTabNormal:require('../img/icon_my_gray.png'),
    myTabClick:require('../img/icon_my_blue.png'),
    location:require('../img/icon_location_white.png'),
    arrow:require('../img/icon_arrow_down_white.png'),
    search:require('../img/icon_search.png'),
    weather:require('../img/icon_weather.png'),
  },
  My:{
    head:require('../img/icon_head.png'),
    phone:require('../img/icon_phone.png'),
    order:require('../img/icon_order.png'),
    point:require('../img/icon_point.png'),
    vip:require('../img/icon_vip.png'),
    service:require('../img/icon_sevice.png'),
    notice:require('../img/icon_notice.png'),
    setting:require('../img/icon_setting.png'),
  },
  Shop:{
    cart:require('../img/icon_shopping_cart.png'),
    shopBg:require('../img/bg.jpg'),
  },
  Splash:{
    splash:require('../img/splash.png'),
  },
  Login:{
    showPwd:require('../img/icon_pwd_show_gray.png'),
    hidePwd:require('../img/icon_pwd_hide_gray.png'),
  },
  UserInfo:{
    head:require('../img/icon_head_default.png'),
  },
  PayOnLine:{
    alipay:require('../img/icon_alipay.png'),
    wechat:require('../img/icon_wechat_pay.png'),
  },
  ServiceCenter:{
    phone:require('../img/icon_phone_green.png'),
  },
}
